### ISSUE TITLE
ValueError: Unknown hyperparameter type for preset

### ISSUE THREAD

**Issue by harirawat** [IEEE-NITK/Neural-Voice-Cloning#2]
As mentioned in the instructions, I have downloaded the pre-trained model and added the contents of the folder back to the repo https://github.com/r9y9/deepvoice3_pytorch (replacing synthesis.py file).

After this, I am running the following command
```python synthesis.py --hparams=builder=deepvoice3,preset=presets/deepvoice3_vctk.json 20171222_deepvoice3_vctk108_checkpoint_step000300000.pth sentences.txt output_dir```

On running this, I am getting the following error.
```
Command line args:
 {'--checkpoint-postnet': None,
 '--checkpoint-seq2seq': None,
 '--file-name-suffix': '',
 '--help': False,
 '--hparams': 'builder=deepvoice3,preset=presets/deepvoice3_vctk.json',
 '--max-decoder-steps': '500',
 '--output-html': False,
 '--replace_pronunciation_prob': '0.0',
 '--speaker_id': None,
 '<checkpoint>': '20171222_deepvoice3_vctk108_checkpoint_step000300000.pth',
 '<dst_dir>': 'output_dir',
 '<text_list_file>': 'sentences.txt'}
Traceback (most recent call last):
  File "synthesis.py", line 114, in <module>
    hparams.parse(args["--hparams"])
  File "C:\Users\aakhya.singh\Downloads\deepvoice3_pytorch-master\deepvoice3_pytorch-master\hparam_tf\hparam.py", line 543, in parse
    values_map = parse_values(values, type_map)
  File "C:\Users\aakhya.singh\Downloads\deepvoice3_pytorch-master\deepvoice3_pytorch-master\hparam_tf\hparam.py", line 263, in parse_values
    raise ValueError('Unknown hyperparameter type for %s' % name)
ValueError: Unknown hyperparameter type for preset
```

Can anyone tell me what I am doing wrong? Do we also need to train the pre-trained model before running this command?

**Comment by deeepgandhi** [comment]
what was the solution? i am facing the same issue
